# Generated by Django 4.2.1 on 2023-05-16 18:58

import core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lft', models.PositiveIntegerField(db_index=True)),
                ('rgt', models.PositiveIntegerField(db_index=True)),
                ('tree_id', models.PositiveIntegerField(db_index=True)),
                ('depth', models.PositiveIntegerField(db_index=True)),
                ('name', models.CharField(max_length=500, verbose_name='Motif name')),
                ('start', models.IntegerField(verbose_name='Start index')),
                ('stop', models.IntegerField(verbose_name='Stop index')),
            ],
            options={
                'verbose_name': 'Motif',
                'verbose_name_plural': 'Motifs',
            },
            bases=(core.mixins.NSNodeMixin, models.Model),
        ),
    ]
